"""
Alembic 迁移脚本模板
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers
revision = 'e01b9892fbe7'
down_revision = '8477ad19053d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(length=256), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1'))
    # 修正：确保已有用户都是活跃状态
    op.execute("UPDATE users SET is_active = 1 WHERE is_active = 0")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'avatar')
    # ### end Alembic commands ###
